export type TemplateCatalogItem = {
    id: string;
    name: string;
    desc: string;
    accent: string;
    eyebrow: string;
    mood: string;
    image?: string;
    tier: 'free' | 'premium';
    previewGradient: string;
};

export type TemplateFilter = 'all' | 'classic' | 'modern' | 'romantic' | 'destination' | 'bold';
export type TemplateRecommendationInput = {
    mood?: 'timeless' | 'soft' | 'clean' | 'dramatic' | 'playful';
    venue?: 'ballroom' | 'garden' | 'beach' | 'city' | 'intimate';
    priority?: 'photos' | 'schedule' | 'rsvp' | 'story';
};

const TEMPLATE_FILTERS: Record<Exclude<TemplateFilter, 'all'>, readonly string[]> = {
    classic: ['classic', 'traditional', 'elegance', 'vintage', 'royal', 'artdeco', 'chateau', 'baroque', 'estate', 'mizuhiki', 'classyphoto', 'streamline', 'marble', 'kimono', 'seigaiha', 'asanoha', 'camellia', 'snowwhite', 'emerald', 'washipaper', 'linea', 'heritage', 'oldpaper', 'truelove', 'hanaume', 'letter', 'japan', 'akamatsu'],
    modern: ['minimal', 'timeline', 'rsvpfocus', 'vogue', 'editorial', 'kinfolk', 'neobrutalist', 'highfashion', 'bauhaus', 'atelier', 'papercut', 'neumorphism', 'magazinecover', 'museum', 'frostedglass', 'duotone', 'splash', 'teaceremony', 'notepaper', 'weddingtimes', 'linea', 'passport', 'fluidmodern', 'airport', 'noweddingnolife', 'minimumstyle', 'modernsquare', 'growthtale'],
    romantic: ['romantic', 'whimsical', 'sakura', 'garden', 'rustic', 'boho', 'glassbotanical', 'cottagecore', 'storybook', 'petal-note', 'lovescript', 'palefloral', 'aromabotanical', 'mellowwave', 'flowerflow', 'luxeheart', 'faintblur', 'hydrangea', 'anemone', 'holynight', 'mimosa', 'mistveil', 'sunflower', 'enchanted', 'lapin', 'daisygarden', 'springrise', 'arrangeflowers', 'innocentpetals', 'bluebird', 'gardenwedding', 'music', 'weddingcake', 'kasumi'],
    destination: ['elopement', 'tropical', 'cinematic', 'film', 'amalfi', 'desertmirage', 'travelogue', 'nordicdrift', 'sunsetriviera', 'coastal-vow', 'lunette', 'polaroid', 'teaceremony', 'oceanblue', 'forest', 'mermaidbeach', 'coralsea', 'yellowsummer', 'oceanus', 'passport', 'airport', 'deeporange', 'naturalcamper', 'konatsu', 'balloonrelease'],
    bold: ['luxury', 'midnight', 'urban', 'glitch', 'vogue', 'editorial', 'gothicnoir', 'discofever', 'stargazer', 'cyberromantic', 'lofifilm', 'magazinecover', 'astronomy', 'splash', 'holynight', 'camellia', 'petlove', 'jazz', 'planetarium', 'emerald', 'retroflower', 'clearblue', 'musicfest', 'botanicalgreen', 'noweddingnolife', 'oceanus', 'enchanted', 'gradientleaf', 'royalblue', 'akamatsu', 'hanaume'],
};

export function templateMatchesFilter(templateId: string, filter: TemplateFilter) {
    return filter === 'all' || TEMPLATE_FILTERS[filter].includes(templateId);
}

export function recommendTemplateIds(input: TemplateRecommendationInput) {
    const signals: Record<string, readonly string[]> = {
        'mood:timeless': ['classic', 'traditional', 'elegance', 'royal', 'chateau', 'baroque'],
        'mood:soft': ['romantic', 'sakura', 'garden', 'whimsical', 'glassbotanical', 'cottagecore', 'kinfolk'],
        'mood:clean': ['minimal', 'editorial', 'timeline', 'rsvpfocus', 'kinfolk', 'bauhaus', 'japandi'],
        'mood:dramatic': ['luxury', 'midnight', 'cinematic', 'artdeco', 'gothicnoir', 'highfashion', 'stargazer'],
        'mood:playful': ['boho', 'tropical', 'whimsical', 'glitch', 'neobrutalist', 'discofever', 'storybook'],
        'venue:ballroom': ['classic', 'luxury', 'royal', 'artdeco', 'baroque', 'chateau'],
        'venue:garden': ['garden', 'romantic', 'sakura', 'boho', 'glassbotanical', 'cottagecore'],
        'venue:beach': ['tropical', 'elopement', 'boho', 'cinematic', 'amalfi', 'sunsetriviera'],
        'venue:city': ['urban', 'editorial', 'vogue', 'minimal', 'neobrutalist', 'highfashion', 'bauhaus'],
        'venue:intimate': ['elopement', 'minimal', 'romantic', 'vintage', 'kinfolk', 'japandi', 'nordicdrift'],
        'priority:photos': ['editorial', 'cinematic', 'film', 'vogue', 'highfashion', 'lofifilm', 'sunsetriviera'],
        'priority:schedule': ['timeline', 'minimal', 'classic', 'elegance', 'neobrutalist', 'nordicdrift'],
        'priority:rsvp': ['rsvpfocus', 'minimal', 'timeline', 'classic', 'neobrutalist', 'travelogue'],
        'priority:story': ['romantic', 'vintage', 'film', 'garden', 'storybook', 'travelogue', 'cottagecore'],
    };
    const scores = new Map<string, number>();
    for (const [key, value] of Object.entries(input)) {
        if (!value) continue;
        signals[`${key}:${value}`]?.forEach((id, rank) => scores.set(id, (scores.get(id) || 0) + 5 - rank));
    }
    return [...scores.entries()].sort((a, b) => b[1] - a[1]).map(([id]) => id).slice(0, 4);
}

export type TemplateStyleVariant = {
    id: string;
    templateId: string;
    variationKey: 'v1' | 'v2' | 'v3' | 'v4' | 'v5';
    name: string;
    desc: string;
    source?: string;
    accent: string;
    heroLayout: string;
    typography: string;
    sectionArrangement: string;
    galleryStyle: string;
    buttonStyle: string;
    backgroundDesign: string;
    rsvpStyle: string;
    mobileLayout: string;
    previewGradient?: string;
};

export const DEFAULT_TEMPLATE_STYLE = 'default';

export const CLASSIC_VARIATIONS: TemplateStyleVariant[] = [
    {
        id: 'classic_v1',
        templateId: 'classic',
        variationKey: 'v1',
        name: 'Timeless Grand Centered (V1)',
        desc: 'Centered portrait hero overlay with elegant serif names, gold dividers, and glassmorphism pill buttons.',
        accent: '#C08081',
        heroLayout: 'Centered Overlay Hero with Gold Divider',
        typography: 'Classic Serif (Cinzel / Playfair) & Clean Sans (Inter)',
        sectionArrangement: 'Standard Story Flow (Hero -> Video -> Bio -> Details -> Countdown -> Timeline -> Gallery -> Attire -> FAQ -> Gift -> RSVP)',
        galleryStyle: 'Balanced Masonry Grid with smooth light-box',
        buttonStyle: 'Rounded Glassmorphism Pill (border border-white/50 bg-black/20 backdrop-blur)',
        backgroundDesign: 'Soft Warm Cream with Subtle Top Radial Gradient',
        rsvpStyle: 'Embedded Centered Glass Card Form',
        mobileLayout: 'Standard Vertical Responsive Stack with Floating Action Bar',
        previewGradient: 'linear-gradient(135deg, #fff9f5 0%, #f8eeea 55%, #ecd4d9 100%)',
    },
    {
        id: 'classic_v2',
        templateId: 'classic',
        variationKey: 'v2',
        name: 'Split-Screen Modern Editorial (V2)',
        desc: 'High-contrast 50/50 split hero with photography on left, bold typography on right, and filmstrip gallery.',
        accent: '#8F394A',
        heroLayout: '50/50 Asymmetric Split-Screen Hero',
        typography: 'Bold Display Serif (Fraunces / Bodoni) & High-Contrast Grotesk Sans',
        sectionArrangement: 'Story-First Flow (Hero -> Bio -> Gallery -> Video -> Details -> Timeline -> RSVP -> FAQ -> Gift)',
        galleryStyle: 'Horizontal Filmstrip / Carousel with subtle page counters',
        buttonStyle: 'Sharp Gold-Bordered Box (rounded-none border-2 border-primary uppercase)',
        backgroundDesign: 'High-Contrast Ivory & Noir Duo-Tone with clean accent borders',
        rsvpStyle: 'Side-by-Side Photo & Interactive RSVP Form Card',
        mobileLayout: 'Card-based full-width mobile sections with sticky top header',
        previewGradient: 'linear-gradient(135deg, #2b1f24 0%, #4a2830 50%, #8f394a 100%)',
    },
    {
        id: 'classic_v3',
        templateId: 'classic',
        variationKey: 'v3',
        name: 'Floating Glass Romance (V3)',
        desc: 'Atmospheric blurred hero with an elevated glassmorphism card, polaroid stack gallery, and soft script accents.',
        accent: '#D9777F',
        heroLayout: 'Elevated Floating Glassmorphism Hero Card',
        typography: 'Soft Romantic Script (Pinyon Script / Alex Brush) & Light Serif',
        sectionArrangement: 'Schedule & Venue Flow (Hero -> Details -> Countdown -> Timeline -> Bio -> Video -> Gallery -> RSVP -> Gift)',
        galleryStyle: 'Polaroid Stack Collage with interactive tilt effects',
        buttonStyle: 'Soft Gradient Pill with Hover Elevation (bg-gradient-to-r from-primary to-rose-400 shadow-lg)',
        backgroundDesign: 'Textured Linen look with subtle floating vector flower accents',
        rsvpStyle: 'Elevated Modal-Style Card with ornamental gold corners',
        mobileLayout: 'Accordion-style expandable mobile sections with quick jump pill tabs',
        previewGradient: 'linear-gradient(135deg, #fff0f3 0%, #fcd5ce 50%, #f8edeb 100%)',
    },
    {
        id: 'classic_v4',
        templateId: 'classic',
        variationKey: 'v4',
        name: 'Magazine Monogram Grid (V4)',
        desc: 'Architectural header featuring large monogram mark, offset 3-photo hero grid, and magazine 2x3 gallery.',
        accent: '#9A5B64',
        heroLayout: 'Monogram Header & Asymmetric 3-Photo Hero Grid',
        typography: 'Modern Editorial Sans (Syne / Outfit) & Bold Bodoni Headings',
        sectionArrangement: 'Media Showcase Flow (Hero -> Video -> Gallery -> Bio -> Details -> Timeline -> Gift -> RSVP)',
        galleryStyle: '2x3 Asymmetric Magazine Grid with full-width highlight banner',
        buttonStyle: 'Underlined Accent Link with Motion Dot (border-b-2 border-primary uppercase font-serif)',
        backgroundDesign: 'Ultra-clean Pure White Canvas with fine line dividers',
        rsvpStyle: 'Step-by-Step Interactive RSVP Wizard Cards',
        mobileLayout: 'Fullscreen Mobile Cards with touch-swipe navigation indicators',
        previewGradient: 'linear-gradient(135deg, #f7f7f7 0%, #e3e3e3 50%, #9a5b64 100%)',
    },
    {
        id: 'classic_v5',
        templateId: 'classic',
        variationKey: 'v5',
        name: 'Minimalist Couture (V5)',
        desc: 'Oversized typography header with inline countdown bar, minimal 3-column grid, and shadow pill buttons.',
        accent: '#5A2A32',
        heroLayout: 'Pure Typography Oversized Banner with Inline Countdown',
        typography: 'Minimalist Sans Grotesk (Space Grotesk / Inter) & Serif Accents',
        sectionArrangement: 'RSVP First Flow (Hero -> RSVP -> Countdown -> Details -> Timeline -> Bio -> Gallery -> Gift)',
        galleryStyle: 'Clean Minimalist 3-Column Grid with hover zoom effects',
        buttonStyle: 'Dual-tone Shadow Pill (rounded-2xl bg-foreground text-background shadow-[4px_4px_0px_0px_rgba(0,0,0,1)])',
        backgroundDesign: 'Soft Motif-tinted gradient with organic wave section separators',
        rsvpStyle: 'Minimalist Bottom Drawer RSVP Card with quick response buttons',
        mobileLayout: 'Single-column clean scroll with extra large touch targets',
        previewGradient: 'linear-gradient(135deg, #faf6f0 0%, #f0e6d8 50%, #5a2a32 100%)',
    },
];

export const TEMPLATE_STYLE_VARIANTS: TemplateStyleVariant[] = [
    ...CLASSIC_VARIATIONS,
    {
        id: 'luxury-planner',
        templateId: 'luxury',
        variationKey: 'v2',
        name: 'Luxury Planner',
        desc: 'Ivory, champagne, editorial spacing, and wedding-planner polish inspired by luxury landing pages.',
        source: 'Nicepage wedding landing reference',
        accent: '#B9975B',
        heroLayout: 'Full Bleed Luxury Frame',
        typography: 'Luxe Serif & High Contrast Sans',
        sectionArrangement: 'Editorial Schedule Flow',
        galleryStyle: 'Masonry Grid',
        buttonStyle: 'Gold Bordered Pill',
        backgroundDesign: 'Ivory & Champagne',
        rsvpStyle: 'Embedded Luxe Form',
        mobileLayout: 'Responsive Stack',
    },
    {
        id: 'editorial-photo',
        templateId: 'editorial',
        variationKey: 'v2',
        name: 'Editorial Photo',
        desc: 'Photography-led hero composition with quiet captions and magazine-style image rhythm.',
        source: 'Nicepage photographer references',
        accent: '#2F2A27',
        heroLayout: 'Photo Focus Split',
        typography: 'Editorial Serif',
        sectionArrangement: 'Gallery Showcase Flow',
        galleryStyle: 'Asymmetric Magazine Grid',
        buttonStyle: 'Minimal Border Button',
        backgroundDesign: 'Pure White Canvas',
        rsvpStyle: 'Minimal Form Card',
        mobileLayout: 'Full-width Cards',
    },
    {
        id: 'romantic-estate',
        templateId: 'romantic',
        variationKey: 'v2',
        name: 'Romantic Estate',
        desc: 'Soft estate romance with airy type, warm neutrals, and refined storybook pacing.',
        source: 'Nicepage romantic wedding references',
        accent: '#B97983',
        heroLayout: 'Floating Glass Card',
        typography: 'Romantic Script & Serif',
        sectionArrangement: 'Story First Flow',
        galleryStyle: 'Polaroid Collage',
        buttonStyle: 'Gradient Soft Pill',
        backgroundDesign: 'Linen Texture with Floral Accents',
        rsvpStyle: 'Modal Style Card',
        mobileLayout: 'Expandable Accordion',
    },
];

/**
 * Returns 5 distinct design variations for any template.
 * For templates with bespoke variation definitions (like `classic`), returns those.
 * Generates 5 structured variations for other template IDs.
 */
export function getTemplateStyleVariants(templateId?: string): TemplateStyleVariant[] {
    const targetId = (templateId || 'classic').toLowerCase();
    const explicit = TEMPLATE_STYLE_VARIANTS.filter((variant) => variant.templateId === targetId);

    if (explicit.length >= 5) {
        return explicit;
    }

    // Default template accent map fallback
    const templateMeta = TEMPLATES.find((t) => t.id === targetId);
    const accent = templateMeta?.accent || '#C08081';

    const defaultFive: TemplateStyleVariant[] = [
        {
            id: 'default',
            templateId: targetId,
            variationKey: 'v1',
            name: `${templateMeta?.name || 'Classic'} Original (V1)`,
            desc: 'The original signature layout with centered hero, standard section ordering, and standard gallery.',
            accent,
            heroLayout: 'Centered Hero Overlay',
            typography: 'Signature Template Fonts',
            sectionArrangement: 'Standard Linear Flow',
            galleryStyle: 'Standard Grid',
            buttonStyle: 'Signature Pill Button',
            backgroundDesign: 'Signature Theme Background',
            rsvpStyle: 'Standard Embedded RSVP Card',
            mobileLayout: 'Standard Responsive Stack',
        },
        {
            id: `${targetId}_v2`,
            templateId: targetId,
            variationKey: 'v2',
            name: 'Split-Screen Modern Editorial (V2)',
            desc: 'Asymmetric 50/50 split hero with photography focus, horizontal filmstrip gallery, and sharp border buttons.',
            accent,
            heroLayout: '50/50 Asymmetric Split Hero',
            typography: 'High-Contrast Bold Display Serif & Grotesk Sans',
            sectionArrangement: 'Story-First Priority Flow',
            galleryStyle: 'Horizontal Filmstrip Carousel',
            buttonStyle: 'Sharp Gold-Bordered Box Button',
            backgroundDesign: 'High-Contrast Duo-Tone Background',
            rsvpStyle: 'Side-by-Side Photo & Interactive Form',
            mobileLayout: 'Card-based Mobile Sections with Sticky Header',
        },
        {
            id: `${targetId}_v3`,
            templateId: targetId,
            variationKey: 'v3',
            name: 'Floating Glass Romance (V3)',
            desc: 'Elevated glassmorphism hero card over atmospheric backdrop with polaroid collage and soft script accents.',
            accent,
            heroLayout: 'Elevated Glassmorphism Floating Hero Card',
            typography: 'Soft Romantic Script & Light Serif',
            sectionArrangement: 'Schedule & Venue Priority Flow',
            galleryStyle: 'Polaroid Stack Interactive Collage',
            buttonStyle: 'Soft Gradient Pill with Hover Lift',
            backgroundDesign: 'Textured Linen Canvas with Vector Accents',
            rsvpStyle: 'Elevated Modal Card with Gold Corners',
            mobileLayout: 'Accordion-style Mobile Sections with Quick Jump Tabs',
        },
        {
            id: `${targetId}_v4`,
            templateId: targetId,
            variationKey: 'v4',
            name: 'Magazine Monogram Grid (V4)',
            desc: 'Monogram header banner with asymmetric 3-photo hero grid, 2x3 magazine layout, and underlined accent links.',
            accent,
            heroLayout: 'Monogram Header & Asymmetric 3-Photo Hero Grid',
            typography: 'Modern Editorial Sans & Bold Bodoni Serif',
            sectionArrangement: 'Media Showcase Priority Flow',
            galleryStyle: '2x3 Asymmetric Magazine Grid',
            buttonStyle: 'Underlined Accent Link with Motion Indicator',
            backgroundDesign: 'Pure Light Minimalist Canvas',
            rsvpStyle: 'Step-by-Step Interactive Form Cards',
            mobileLayout: 'Fullscreen Mobile Swipe Cards',
        },
        {
            id: `${targetId}_v5`,
            templateId: targetId,
            variationKey: 'v5',
            name: 'Minimalist Couture (V5)',
            desc: 'Pure typography hero banner with inline countdown bar, minimal 3-column grid, and dual-tone shadow pill buttons.',
            accent,
            heroLayout: 'Pure Typography Banner with Inline Countdown',
            typography: 'Minimalist Sans Grotesk & Elegant Serif Accents',
            sectionArrangement: 'RSVP-First Priority Flow',
            galleryStyle: 'Minimalist 3-Column Grid with Zoom Effects',
            buttonStyle: 'Dual-Tone Shadow Pill Button',
            backgroundDesign: 'Soft Motif Gradient with Organic Wave Dividers',
            rsvpStyle: 'Minimalist Bottom Drawer RSVP Card',
            mobileLayout: 'Single-Column Clean Scroll with Big Touch Targets',
        },
    ];

    // Combine explicit and dynamic variations to ensure 5 total unique variations
    const map = new Map<string, TemplateStyleVariant>();
    explicit.forEach((v) => map.set(v.id, v));
    defaultFive.forEach((v) => {
        if (!map.has(v.id)) map.set(v.id, v);
    });

    return Array.from(map.values()).slice(0, 5);
}

export function isTemplateStyleAvailable(templateId?: string, styleId?: string) {
    if (!styleId || styleId === DEFAULT_TEMPLATE_STYLE || styleId === 'classic_v1' || styleId === 'v1') return true;
    const variants = getTemplateStyleVariants(templateId);
    return variants.some((variant) => variant.id === styleId);
}

export function getTemplateStyleLabel(styleId?: string) {
    if (!styleId || styleId === DEFAULT_TEMPLATE_STYLE) return 'Original (V1)';
    const found = TEMPLATE_STYLE_VARIANTS.find((variant) => variant.id === styleId);
    if (found) return found.name;
    if (styleId.includes('_v2') || styleId === 'v2') return 'Split-Screen Modern (V2)';
    if (styleId.includes('_v3') || styleId === 'v3') return 'Floating Glass Romance (V3)';
    if (styleId.includes('_v4') || styleId === 'v4') return 'Magazine Monogram Grid (V4)';
    if (styleId.includes('_v5') || styleId === 'v5') return 'Minimalist Couture (V5)';
    return 'Original (V1)';
}

export const FREE_TEMPLATE_IDS = [
    'classic',
    'minimal',
    'romantic',
    'luxury',
    'elopement',
    'traditional',
    'timeline',
    'rsvpfocus',
    'cinematic',
    'elegance',
    'artdeco',
    'boho',
    'whimsical',
    'urban',
    'tropical',
    'midnight',
    'sakura',
    'vogue',
    'rustic',
    'film',
    'glitch',
    'vintage',
    'editorial',
    'royal',
    'garden',
    'palefloral',
    'classyphoto',
    'mellowwave',
    'streamline',
    'flowerflow',
    'polaroid',
    'seigaiha',
    'hydrangea',
    'notepaper',
] as const;
export const LANDING_TEMPLATE_IDS = ['classic', 'minimal', 'boho', 'royal', 'midnight', 'tropical'] as const;
export const SHOWCASE_TEMPLATE_IDS = ['classic', 'minimal', 'royal', 'boho', 'urban', 'tropical'] as const;

export const TEMPLATES: TemplateCatalogItem[] = [
    {
        id: 'classic',
        name: 'Classic Elegance',
        desc: 'Timeless, centered layout with graceful serif typography.',
        accent: '#C08081',
        eyebrow: 'Timeless Romance',
        mood: 'Ivory, rose, and heirloom softness',
        image: '/templates/classic.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff9f5 0%, #f8eeea 55%, #ecd4d9 100%)',
    },
    {
        id: 'minimal',
        name: 'Modern Minimal',
        desc: 'Clean lines, high contrast, and restrained luxury.',
        accent: '#3A2A2D',
        eyebrow: 'Clean Editorial',
        mood: 'Quiet contrast and gallery-grade whitespace',
        image: '/templates/minimal.png',
        tier: 'free',
        previewGradient: 'linear-gradient(145deg, #ffffff 0%, #f4f2ef 48%, #e7dfda 100%)',
    },
    {
        id: 'romantic',
        name: 'Romantic',
        desc: 'Soft textures, script details, and nostalgic framing.',
        accent: '#B85C7A',
        eyebrow: 'Soft Love Story',
        mood: 'Powder blush, poetry, and candlelight',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8fb 0%, #f8e6ee 55%, #eed3df 100%)',
    },
    {
        id: 'luxury',
        name: 'Luxury Editorial',
        desc: 'Magazine-style composition with fashion-house drama.',
        accent: '#C5A059',
        eyebrow: 'Fashion House',
        mood: 'Black lacquer and brushed gold',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #080808 0%, #18130f 50%, #382914 100%)',
    },
    {
        id: 'elopement',
        name: 'Intimate Elopement',
        desc: 'A heartfelt layout focused on the couple and their journey.',
        accent: '#6B7A62',
        eyebrow: 'Quiet Escape',
        mood: 'Alpine light and understated intimacy',
        tier: 'free',
        previewGradient: 'linear-gradient(140deg, #f7f4ee 0%, #dfe6d7 50%, #bcc9b2 100%)',
    },
    {
        id: 'traditional',
        name: 'Traditional Ceremonial',
        desc: 'Ornate details and majestic styling for formal celebrations.',
        accent: '#8F6A45',
        eyebrow: 'Grand Ceremony',
        mood: 'Ceremonial warmth and polished heritage',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff7ed 0%, #ecd9c4 55%, #caa783 100%)',
    },
    {
        id: 'timeline',
        name: 'Timeline Based',
        desc: 'Structured around the flow of the day and guest clarity.',
        accent: '#4D5B7C',
        eyebrow: 'Structured Flow',
        mood: 'Architectural rhythm with calm precision',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 52%, #c9d4e7 100%)',
    },
    {
        id: 'rsvpfocus',
        name: 'RSVP First',
        desc: 'Guest confirmation takes center stage with a crisp layout.',
        accent: '#A0616A',
        eyebrow: 'Guest Forward',
        mood: 'High-conversion clarity with elegance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff9f7 0%, #f3e4e4 52%, #dfc4c8 100%)',
    },
    {
        id: 'cinematic',
        name: 'Media Forward',
        desc: 'A motion-led layout for sharing your love story in filmic style.',
        accent: '#C7704D',
        eyebrow: 'Cinema Frame',
        mood: 'Moody amber light and widescreen drama',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #0f1116 0%, #241b17 50%, #533427 100%)',
    },
    {
        id: 'elegance',
        name: 'Minimal Elegant',
        desc: 'Refined typography and sophisticated restraint.',
        accent: '#9B7A5E',
        eyebrow: 'Quiet Luxe',
        mood: 'Soft taupe and couture spacing',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffcf8 0%, #f0e6dc 55%, #dcc9b6 100%)',
    },
    {
        id: 'artdeco',
        name: 'Art Deco Gold',
        desc: 'Geometric framing and opulent metallic accents.',
        accent: '#C5A059',
        eyebrow: 'Gilded Geometry',
        mood: 'Jazz-era glamour and symmetry',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #121212 0%, #241d15 50%, #5d4520 100%)',
    },
    {
        id: 'boho',
        name: 'Boho Dream',
        desc: 'Organic shapes, earthy color, and warm, freeform romance.',
        accent: '#A56D52',
        eyebrow: 'Earthy Poetry',
        mood: 'Clay, linen, and artisanal warmth',
        image: '/templates/boho.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff7ef 0%, #edd8c6 50%, #d4a27e 100%)',
    },
    {
        id: 'whimsical',
        name: 'Whimsical Garden',
        desc: 'Playful motion and airy floral delight.',
        accent: '#8D7BC4',
        eyebrow: 'Storybook Bloom',
        mood: 'Petal mist and playful detail',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff9fd 0%, #ebdef8 50%, #cdb9f3 100%)',
    },
    {
        id: 'urban',
        name: 'Industrial Urban',
        desc: 'Raw textures, stark contrast, and fashion-week edge.',
        accent: '#FF4D5A',
        eyebrow: 'City After Dark',
        mood: 'Concrete, chrome, and neon tension',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #090909 0%, #202020 55%, #4f171d 100%)',
    },
    {
        id: 'tropical',
        name: 'Tropical Paradise',
        desc: 'Vibrant color, lush framing, and destination energy.',
        accent: '#0B8F7B',
        eyebrow: 'Destination Glow',
        mood: 'Sea glass, palms, and sunset freshness',
        image: '/templates/tropical.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #effcf8 0%, #d1f4ee 48%, #7fd7c8 100%)',
    },
    {
        id: 'midnight',
        name: 'Midnight Luxury',
        desc: 'A premium dark theme with luminous gold detailing.',
        accent: '#CFB53B',
        eyebrow: 'After-Hours Luxe',
        mood: 'Champagne glow over black velvet',
        image: '/templates/midnight.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #05060a 0%, #12192d 48%, #3d3416 100%)',
    },
    {
        id: 'sakura',
        name: 'Sakura Blossom',
        desc: 'Cherry blossom softness with graceful Japanese notes.',
        accent: '#D88DA9',
        eyebrow: 'Bloom Season',
        mood: 'Petal pink and spring air',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8fb 0%, #f7e4ee 55%, #edbfd3 100%)',
    },
    {
        id: 'vogue',
        name: 'High Fashion',
        desc: 'Asymmetry, large type, and runway-confidence.',
        accent: '#111111',
        eyebrow: 'Runway Edit',
        mood: 'Monochrome confidence with couture pacing',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #efefef 52%, #d7d7d7 100%)',
    },
    {
        id: 'rustic',
        name: 'Rustic Charm',
        desc: 'Warm timber tones, string-light softness, and cozy romance.',
        accent: '#8C6446',
        eyebrow: 'Barn Glow',
        mood: 'Honey wood and candlelit comfort',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8ee 0%, #ead9c4 52%, #bb8e60 100%)',
    },
    {
        id: 'film',
        name: 'Retro Film',
        desc: 'Grain, analog edges, and memory-like nostalgia.',
        accent: '#B4875C',
        eyebrow: 'Analog Memory',
        mood: 'Warm grain and silver halide softness',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #1b1815 0%, #5b4734 52%, #c49c74 100%)',
    },
    {
        id: 'glitch',
        name: 'Cyber Glitch',
        desc: 'Digital texture, chromatic accents, and avant-garde energy.',
        accent: '#4EF2E0',
        eyebrow: 'Neo Signal',
        mood: 'Cyan, magenta, and digital pulse',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #05070f 0%, #11182c 48%, #2a0f3d 100%)',
    },
    {
        id: 'vintage',
        name: 'Vintage Postcard',
        desc: 'Antique paper, old-world lettering, and keepsake charm.',
        accent: '#A67C52',
        eyebrow: 'Keepsake Paper',
        mood: 'Faded parchment and heirloom stamps',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fcf7ef 0%, #e7d8c4 55%, #c4a179 100%)',
    },
    {
        id: 'editorial',
        name: 'Editorial Chic',
        desc: 'Large-format imagery with a luxury magazine attitude.',
        accent: '#1E1E1E',
        eyebrow: 'Magazine Cover',
        mood: 'Hero photography and stark elegance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fefefe 0%, #ececec 50%, #d7d0cb 100%)',
    },
    {
        id: 'royal',
        name: 'Royal Proclamation',
        desc: 'Majestic darkness with heraldic gold refinement.',
        accent: '#D6B87C',
        eyebrow: 'Regal Drama',
        mood: 'Velvet halls and ceremonial gold',
        image: '/templates/royal.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #0c0c0c 0%, #181818 44%, #49351d 100%)',
    },
    {
        id: 'garden',
        name: 'Secret Garden',
        desc: 'Botanical elegance with lush, layered greenery.',
        accent: '#537A57',
        eyebrow: 'Botanical Estate',
        mood: 'Green canopies and conservatory light',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f8fbf5 0%, #d8e7d1 52%, #9fba94 100%)',
    },
    {
        id: 'heirloom',
        name: 'Heirloom Watercolor',
        desc: 'Illustrated invitation details with soft paper, botanical framing, and graceful pacing.',
        accent: '#6A7D54',
        eyebrow: 'Painted Invitation',
        mood: 'Watercolor botanicals and a handwritten keepsake',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffdf6 0%, #eef1df 48%, #b7c59f 100%)',
    },
    {
        id: 'estate',
        name: 'The Estate',
        desc: 'Understated country-house luxury with ample space for a multi-day celebration.',
        accent: '#7D705B',
        eyebrow: 'Country House',
        mood: 'Limestone, cream linen, and quiet grandeur',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fbf8f1 0%, #e5ded0 52%, #b9ab93 100%)',
    },
    {
        id: 'moonlit',
        name: 'Moonlit Romance',
        desc: 'A cinematic dark invitation with luminous type and after-hours polish.',
        accent: '#D8C494',
        eyebrow: 'After Dark',
        mood: 'Black silk, champagne light, and midnight florals',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #090a10 0%, #1b1d2c 50%, #54472c 100%)',
    },
    {
        id: 'saffron',
        name: 'Saffron Ceremony',
        desc: 'A celebratory heritage design for colorful, multi-event wedding weekends.',
        accent: '#B65B2A',
        eyebrow: 'Heritage Celebration',
        mood: 'Saffron, marigold, and jewel-toned ceremony',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff4df 0%, #f2c785 50%, #b85d31 100%)',
    },
    {
        id: 'cinema-noir',
        name: 'Cinema Noir',
        desc: 'Film-still imagery, rich contrast, and a dramatic love-story reveal.',
        accent: '#C78A63',
        eyebrow: 'Love on Film',
        mood: 'Amber grain, smoke, and widescreen romance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #070809 0%, #241a18 54%, #714735 100%)',
    },
    {
        id: 'modern-vow',
        name: 'Modern Vow',
        desc: 'Fresh typography and refined utility for a contemporary wedding weekend.',
        accent: '#437E70',
        eyebrow: 'Contemporary Union',
        mood: 'Soft mint, clean type, and purposeful detail',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fbfffd 0%, #dceee8 52%, #93c4b5 100%)',
    },
    {
        id: 'atelier',
        name: 'Atelier Editorial',
        desc: 'A fashion-led composition for couples who want a magazine-worthy celebration.',
        accent: '#332B2B',
        eyebrow: 'The Fashion Edit',
        mood: 'Studio white, ink, and art-directed photography',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #e9e4df 50%, #b8aaa0 100%)',
    },
    {
        id: 'wildflower',
        name: 'Wildflower Weekend',
        desc: 'Relaxed color, organic forms, and a warm destination-wedding spirit.',
        accent: '#B46C52',
        eyebrow: 'Free-Spirited Love',
        mood: 'Sun-baked clay, meadow blooms, and long tables',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff7ee 0%, #edd3bc 50%, #d69069 100%)',
    },
    {
        id: 'regency',
        name: 'Regency Ball',
        desc: 'Formal portraiture and gilded ornament for a black-tie, ballroom celebration.',
        accent: '#C8A962',
        eyebrow: 'Black Tie Affair',
        mood: 'Deep ink, antique gold, and grand entrances',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #090a0e 0%, #20202a 50%, #665229 100%)',
    },
    {
        id: 'lovescript',
        name: 'Love Script',
        desc: 'An invitation-first design with oversized calligraphy and intimate storytelling.',
        accent: '#B76883',
        eyebrow: 'Written With Love',
        mood: 'Rose paper, fine ink, and handwritten promises',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff9fb 0%, #f3dfe7 50%, #d999b2 100%)',
    },
    {
        id: 'coastal-vow',
        name: 'Coastal Vow',
        desc: 'Fresh ocean color and a relaxed itinerary for destination celebrations.',
        accent: '#2C7891',
        eyebrow: 'By The Sea',
        mood: 'Salt air, crisp linen, and sunset vows',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f5fcfc 0%, #cde9ec 50%, #73afc0 100%)',
    },
    {
        id: 'orchid-noir',
        name: 'Orchid Noir',
        desc: 'A floral after-dark invitation with dramatic contrast and couture energy.',
        accent: '#8D5273',
        eyebrow: 'Evening In Bloom',
        mood: 'Orchid shadows, silk, and a little mystery',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #100b11 0%, #2e1e30 52%, #8d5273 100%)',
    },
    {
        id: 'papercut',
        name: 'Paper Cut',
        desc: 'A graphic, modern invitation built around expressive type and colorful shape.',
        accent: '#E06D48',
        eyebrow: 'Modern Invitation',
        mood: 'Terracotta paper, sharp type, joyful composition',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff9f5 0%, #fae3d8 50%, #e06d48 100%)',
    },
    {
        id: 'celestial',
        name: 'Celestial',
        desc: 'An atmospheric night-sky design for starry, unforgettable celebrations.',
        accent: '#9BADE0',
        eyebrow: 'Written In The Stars',
        mood: 'Constellations, midnight blue, and luminous promise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #11162a 0%, #1e2748 52%, #9bade0 100%)',
    },
    {
        id: 'marigold-house',
        name: 'Marigold House',
        desc: 'A colorful ceremonial design for joyful, multi-day family celebrations.',
        accent: '#C56A16',
        eyebrow: 'Joyful Gathering',
        mood: 'Marigold, music, and generations together',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff6dc 0%, #f8d575 52%, #c56a16 100%)',
    },
    {
        id: 'the-weekend',
        name: 'The Weekend',
        desc: 'An elevated guest-first layout for welcome parties, ceremonies, and brunch.',
        accent: '#5A6C62',
        eyebrow: 'Wedding Weekend',
        mood: 'Country-house ease and thoughtful details',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8faf5 0%, #d9e0d4 52%, #8fa197 100%)',
    },
    {
        id: 'winter-rose',
        name: 'Winter Rose',
        desc: 'Velvet darkness and rose-red detail for an unforgettable winter celebration.',
        accent: '#A33D4A',
        eyebrow: 'Winter Celebration',
        mood: 'Candlelight, velvet, and deep red roses',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #150d11 0%, #341a24 52%, #a33d4a 100%)',
    },
    {
        id: 'gallery',
        name: 'The Gallery',
        desc: 'A considered, art-directed canvas for couples with a creative point of view.',
        accent: '#6C5A46',
        eyebrow: 'Gallery Of Us',
        mood: 'Gallery white, antique brass, and artful imagery',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fbfaf8 0%, #e8e1d7 52%, #aa9278 100%)',
    },
    {
        id: 'petal-note',
        name: 'Petal Note',
        desc: 'A tender, handwritten invitation with blush paper and botanical warmth.',
        accent: '#C8889A',
        eyebrow: 'A Note For You',
        mood: 'Petal pink, gentle script, and a personal welcome',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff9fb 0%, #f6e2e8 52%, #c8889a 100%)',
    },
    {
        id: 'sunset-ceremony',
        name: 'Sunset Ceremony',
        desc: 'Golden-hour warmth and destination energy for celebrations by the horizon.',
        accent: '#D4774F',
        eyebrow: 'Golden Hour',
        mood: 'Warm light, open skies, and an evening to remember',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff6ec 0%, #f5d3a5 52%, #d4774f 100%)',
    },
    // 20 New Trending Styles
    {
        id: 'kinfolk',
        name: 'Kinfolk Atelier',
        desc: 'Quiet luxury, generous whitespace, and fine-line editorial serenity.',
        accent: '#8E8A82',
        eyebrow: 'The Minimal Atelier',
        mood: 'Understated elegance, quiet luxury, and timeless serenity',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fbf9f5 0%, #f3efea 52%, #8e8a82 100%)',
    },
    {
        id: 'neobrutalist',
        name: 'Neo-Brutalist Love',
        desc: 'Bold solid borders, colorful sticker badges, and high-energy bento cards.',
        accent: '#FF5E5B',
        eyebrow: 'Bold & Unapologetic',
        mood: "We're getting hitched! High contrast, big energy, pure joy",
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffdf7 0%, #ffe169 50%, #ff5e5b 100%)',
    },
    {
        id: 'highfashion',
        name: 'High-Fashion Runway',
        desc: 'Magazine-cover split screen, black & white grain, and gilded gold leaf touches.',
        accent: '#D4AF37',
        eyebrow: 'Monochrome Maison',
        mood: 'Haute couture editorial, timeless black & white drama',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #111111 0%, #262626 50%, #d4af37 100%)',
    },
    {
        id: 'glassbotanical',
        name: 'Glassmorphic Flora',
        desc: 'Frosted glass crystal cards, soft luminescence, and floating botanical petals.',
        accent: '#7FA073',
        eyebrow: 'The Lucent Flora',
        mood: 'Frosted crystal luminescence and floating botanical petals',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f7fcf9 0%, #e8f5e9 50%, #7fa073 100%)',
    },
    {
        id: 'cyberromantic',
        name: 'Cyber Romantic',
        desc: 'Holographic glows, soft iridescent halos, and future romanticism.',
        accent: '#FF80BF',
        eyebrow: 'Iridescent Y2K Glam',
        mood: 'Chrome glows, holographic dreamscapes, and future romance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #0b0c10 0%, #2a1b3d 50%, #ff80bf 100%)',
    },
    {
        id: 'amalfi',
        name: 'Amalfi Majolica',
        desc: 'Italian coastal ceramic tiles, sun-drenched lemons, and Mediterranean romance.',
        accent: '#1C4E80',
        eyebrow: 'La Dolce Vita',
        mood: 'Capri lemon groves, majolica tiles, and sunlit coastal vows',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffdf7 0%, #fdf3d6 50%, #1c4e80 100%)',
    },
    {
        id: 'japandi',
        name: 'Japandi Zen',
        desc: 'Washi paper textures, sumi-e ink brush accents, and organic calm.',
        accent: '#8B9A82',
        eyebrow: 'Zen & Naturalis',
        mood: 'Washi textures, organic simplicity, and quiet breathing room',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f2efe9 0%, #eae6dd 50%, #8b9a82 100%)',
    },
    {
        id: 'desertmirage',
        name: 'Desert Mirage',
        desc: 'Adobe terracotta arches, sun-bleached dunes, and warm golden light.',
        accent: '#C86D51',
        eyebrow: 'Sun-Bleached Dune',
        mood: 'Warm terracotta arches, desert agave, and golden hour light',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fbf3e8 0%, #f5e4d3 50%, #c86d51 100%)',
    },
    {
        id: 'chateau',
        name: 'Chateau Rococo',
        desc: 'Toile de Jouy engravings, Parisian chandeliers, and Marie Antoinette blush.',
        accent: '#335C81',
        eyebrow: 'Toile de Jouy',
        mood: 'Gilded ballroom chandeliers, Sèvres blue, and Parisian romance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #faf8f5 0%, #f0e6d2 50%, #335c81 100%)',
    },
    {
        id: 'travelogue',
        name: 'Passport Travelogue',
        desc: 'Boarding pass invitation, vintage airmail edges, and passport stamps.',
        accent: '#C0392B',
        eyebrow: 'The Grand Voyage',
        mood: 'Passport stamps, vintage airmail, and a lifetime of adventures together',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8f6f0 0%, #e6eff5 50%, #c0392b 100%)',
    },
    {
        id: 'gothicnoir',
        name: 'Gothic Noir',
        desc: 'Obsidian black, bordeaux velvet, and moody romantic candlelight.',
        accent: '#9E2A2B',
        eyebrow: 'Midnight Masquerade',
        mood: 'Deep bordeaux velvet, obsidian shadows, and candlelit romance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #0d0e11 0%, #25161c 50%, #9e2a2b 100%)',
    },
    {
        id: 'discofever',
        name: '70s Studio Disco',
        desc: 'Groovy warm curves, spinning vinyl records, and golden dancefloor joy.',
        accent: '#E39B00',
        eyebrow: 'The Golden Groove',
        mood: '70s dancefloor warmth, spinning vinyl records, and golden sparkle',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff8ee 0%, #fce7c8 50%, #e39b00 100%)',
    },
    {
        id: 'baroque',
        name: 'Baroque Gilded',
        desc: 'Ornate gold filigree, royal navy velvet, and regal monogram crests.',
        accent: '#D4AF37',
        eyebrow: 'The Gilded Dynasty',
        mood: 'Heritage crests, royal navy velvet, and 24-karat gold filigree',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #faf7f2 0%, #1a2744 50%, #d4af37 100%)',
    },
    {
        id: 'lofifilm',
        name: 'Lo-Fi 35mm',
        desc: 'Analog film strip slider, Kodak warm glow, and nostalgic candid frames.',
        accent: '#FF9F1C',
        eyebrow: 'Film Strip Nostalgia',
        mood: '35mm grain, Kodak warm amber glow, and honest candid memories',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #181818 0%, #382818 50%, #ff9f1c 100%)',
    },
    {
        id: 'stargazer',
        name: 'Celestial Stargazer',
        desc: 'Zodiac constellation maps, lunar moon phase, and stardust elegance.',
        accent: '#F5D061',
        eyebrow: 'The Cosmic Union',
        mood: 'Zodiac constellations, lunar glow, and love written in the stardust',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #0b0f19 0%, #22193e 50%, #f5d061 100%)',
    },
    {
        id: 'cottagecore',
        name: 'Pressed Herbarium',
        desc: 'Pressed wildflowers, deckle-edge paper, and botanical notebook romance.',
        accent: '#5E7153',
        eyebrow: 'The Herbarium Notebook',
        mood: 'Pressed wildflower petals, botanical gardens, and handwritten vows',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #faf6f0 0%, #ebe2dc 50%, #5e7153 100%)',
    },
    {
        id: 'bauhaus',
        name: 'Bauhaus Artiste',
        desc: 'Bold primary color blocking, geometric grids, and modern Bauhaus composition.',
        accent: '#1D4ED8',
        eyebrow: 'Modern Artiste',
        mood: 'Bauhaus geometry, bold color blocks, and structured artistic love',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #fee2e2 50%, #1d4ed8 100%)',
    },
    {
        id: 'nordicdrift',
        name: 'Nordic Cabin',
        desc: 'Alpine pine warmth, cozy fireplaces, and serene Scandinavian hygge.',
        accent: '#D97706',
        eyebrow: 'Hygge Hearth',
        mood: 'Alpine pines, cozy fireplaces, and warm Scandinavian minimalism',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f7f5f0 0%, #e2e8f0 50%, #d97706 100%)',
    },
    {
        id: 'sunsetriviera',
        name: 'Sunset Riviera',
        desc: 'Multi-color golden hour mesh gradients, champagne toasts, and coastal romance.',
        accent: '#F43F5E',
        eyebrow: 'Golden Hour Glow',
        mood: 'Multi-color sunset mesh gradients, champagne toasts, and warm ocean breeze',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff8f6 0%, #ffe4e6 50%, #f43f5e 100%)',
    },
    {
        id: 'storybook',
        name: 'Storybook Scrapbook',
        desc: 'Keepsake washi tape, tilted memory polaroids, and whimsical notes.',
        accent: '#E07A5F',
        eyebrow: 'Memory Collage',
        mood: 'Washi tapes, keepsake polaroids, and our sweetest story chapters',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8f4eb 0%, #fbece7 50%, #e07a5f 100%)',
    },
    // 10 Brapla-Inspired Designs
    {
        id: 'palefloral',
        name: 'Pale Floral Wildflower',
        desc: 'Watercolor wildflower corner borders, gentle sage & blush tones, and a dedicated countdown clock banner.',
        accent: '#8B9577',
        eyebrow: 'Botanical Keepsake',
        mood: 'Pale blush, sage leaves, and delicate flora',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fbfcf9 0%, #edf1e8 50%, #d5ded0 100%)',
    },
    {
        id: 'classyphoto',
        name: 'Classy Editorial',
        desc: 'Japanese luxury duo-tone bordered couple portrait with high-contrast serif typography.',
        accent: '#8F394A',
        eyebrow: 'Refined Modernity',
        mood: 'Framed couple portrait with high-contrast serif typography',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff7f7 0%, #fae6e9 50%, #d49da7 100%)',
    },
    {
        id: 'mellowwave',
        name: 'Mellow Wave',
        desc: '70s modern retro curves, pastel duo-tone blocks, and undulating wavy section dividers.',
        accent: '#E07A5F',
        eyebrow: 'Fluid Retro Curves',
        mood: 'Undulating wave dividers, warm terracotta, and pastel warmth',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffaf6 0%, #fbece7 50%, #e07a5f 100%)',
    },
    {
        id: 'mizuhiki',
        name: 'Mizuhiki Heritage',
        desc: 'Traditional Japanese ceremonial knot cord symbolizing everlasting union on textured paper.',
        accent: '#C0392B',
        eyebrow: 'Ceremonial Cord',
        mood: 'Crimson & gold Mizuhiki cords symbolizing eternal union',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffaf8 0%, #fadbd8 50%, #c0392b 100%)',
    },
    {
        id: 'neumorphism',
        name: 'Soft Neumorphic 3D',
        desc: 'Tactile embossed/debossed cards, pill buttons with inward depression, and architectural minimalism.',
        accent: '#4F6D7A',
        eyebrow: 'Tactile Modernism',
        mood: 'Soft embossed shadows, pill buttons, and clean architectural minimalism',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f7f9fa 0%, #e8ecef 50%, #4f6d7a 100%)',
    },
    {
        id: 'aromabotanical',
        name: 'Aroma Mist Flora',
        desc: 'Frosted misty veil photo overlay with pressed botanical greenery and clean organic spacing.',
        accent: '#5B7065',
        eyebrow: 'Frosted Herbarium',
        mood: 'Misty veil photo overlay with pressed botanical greenery',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f6f9f7 0%, #e5ece8 50%, #5b7065 100%)',
    },
    {
        id: 'magazinecover',
        name: 'Magazine Fullscreen',
        desc: 'Giant bold display masthead overlaid on full-bleed hero photography with haute editorial attitude.',
        accent: '#111111',
        eyebrow: 'Haute Editorial',
        mood: 'Oversized Abril Fatface masthead over full-bleed portrait photography',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #e5e5e5 50%, #111111 100%)',
    },
    {
        id: 'lunette',
        name: 'Lunette Arch',
        desc: 'Architectural Roman window arch framing for couple photography with warm Mediterranean terracotta tones.',
        accent: '#B85D43',
        eyebrow: 'Roman Window Arch',
        mood: 'Architectural arch framing, warm olive and terracotta Mediterranean tones',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffbf7 0%, #f3e8e2 50%, #b85d43 100%)',
    },
    {
        id: 'museum',
        name: 'Museum Gallery',
        desc: 'Fine-art museum exhibition curation with stark white passe-partout borders and plaque typography.',
        accent: '#2B2D42',
        eyebrow: 'Fine Art Curation',
        mood: 'Fine-art gallery exhibition, stark white borders, and museum pacing',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #f4f4f6 50%, #2b2d42 100%)',
    },
    {
        id: 'frostedglass',
        name: 'Frosted Glass Luminous',
        desc: 'Translucent frosted glass cards, blurred backdrop glows, and floating acrylic badges.',
        accent: '#457B9D',
        eyebrow: 'Lucent Acrylic',
        mood: 'Translucent frosted glass cards, blurred backdrop glows, and floating badges',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f0f7fb 0%, #d8eaf5 50%, #457b9d 100%)',
    },
    {
        id: 'astronomy',
        name: 'Medieval Astronomy',
        desc: 'Antique celestial charts, zodiac constellation maps, golden astrolabes, and deep midnight mystery.',
        accent: '#C5A059',
        eyebrow: 'Celestial Charts',
        mood: 'Deep midnight blue, golden astrolabes, and zodiac constellations',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #0b0f19 0%, #172036 50%, #c5a059 100%)',
    },
    {
        id: 'streamline',
        name: 'Streamline Art Deco',
        desc: 'Continuous metallic hairline borders, Gatsby geometric symmetry, and polished gilded rhythm.',
        accent: '#D4AF37',
        eyebrow: 'Gilded Symmetry',
        mood: 'Continuous metallic hairline borders, Gatsby elegance, and geometric rhythm',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #faf8f5 0%, #f4ede2 50%, #d4af37 100%)',
    },
    {
        id: 'marble',
        name: 'Carrara Marble Luxury',
        desc: 'Travertine stone textures, subtle gold veining, Roman arch framing, and classical grandeur.',
        accent: '#A68A68',
        eyebrow: 'Italian Villa Stone',
        mood: 'Travertine marble stone textures, subtle gold veining, and classical poise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f9f7f4 0%, #ede6dc 50%, #a68a68 100%)',
    },
    {
        id: 'luxeheart',
        name: 'Luxe Heart Romance',
        desc: 'Deep bordeaux velvet, intertwined heart monogram crests, and candlelit romance.',
        accent: '#9E2A2B',
        eyebrow: 'Intertwined Monogram',
        mood: 'Deep bordeaux velvet, intertwined heart crests, and candlelit romance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff9fa 0%, #f5d6d8 50%, #9e2a2b 100%)',
    },
    {
        id: 'flowerflow',
        name: 'Flower Flow Petals',
        desc: 'Cascading cherry and rose blossom petals, curved flowing cards, and fresh spring sunlight.',
        accent: '#D4829A',
        eyebrow: 'Petal Breeze',
        mood: 'Cascading cherry and rose petals, curved flowing cards, and spring light',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffdfb 0%, #fdeef2 50%, #d4829a 100%)',
    },
    {
        id: 'faintblur',
        name: 'Aura Faint Blur',
        desc: 'Diffused pastel sunset orbs, dreamy ethereal luminescence, and glowing romanticism.',
        accent: '#8A6BA8',
        eyebrow: 'Atmospheric Aura',
        mood: 'Diffused pastel sunset orbs, dreamy ethereal luminescence, and modern bliss',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #faf5fd 0%, #eeddf8 50%, #8a6ba8 100%)',
    },
    {
        id: 'splash',
        name: 'Artisan Paint Splash',
        desc: 'Vibrant watercolor paint splatters, dynamic gouache brush strokes, and creative artistic energy.',
        accent: '#E65100',
        eyebrow: 'Joyful Gouache',
        mood: 'Vibrant watercolor paint splatters, dynamic brush strokes, and creative energy',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffbf5 0%, #ffe0b2 50%, #e65100 100%)',
    },
    {
        id: 'polaroid',
        name: 'Polaroid Keepsake',
        desc: 'Cascading stacked polaroids, washi tape corners, and nostalgic handwritten date stamps.',
        accent: '#4A6B82',
        eyebrow: 'Instant Memories',
        mood: 'Cascading stacked polaroids, washi tape corners, and nostalgic handwritten dates',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f9fbfc 0%, #dce8f0 50%, #4a6b82 100%)',
    },
    {
        id: 'kimono',
        name: 'Kimono Washi Heritage',
        desc: 'Ceremonial bridal kimono silk embroidery textures, traditional gold leaf, and timeless poise.',
        accent: '#B71C1C',
        eyebrow: 'Bridal Silk & Washi',
        mood: 'Ceremonial kimono embroidery textures, traditional gold leaf, and timeless poise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fffdfb 0%, #fbe9e7 50%, #b71c1c 100%)',
    },
    {
        id: 'duotone',
        name: 'Duo Edition Split',
        desc: '50/50 dual personality split screen, interlocking initials, and modern high-contrast editorial styling.',
        accent: '#2E4057',
        eyebrow: 'Complementary Vows',
        mood: '50/50 dual personality split screen, interlocking initials, and modern editorial contrast',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #e5ebf2 50%, #2e4057 100%)',
    },
    {
        id: 'seigaiha',
        name: 'Seigaiha Wave Crests',
        desc: 'Auspicious Japanese wave crests symbolizing surges of good fortune, calm seas, and eternal peace.',
        accent: '#1D3557',
        eyebrow: 'Wave of Good Fortune',
        mood: 'Auspicious Japanese wave crests symbolizing calm seas and eternal peace',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f7fafd 0%, #e0ecf8 50%, #1d3557 100%)',
    },
    {
        id: 'asanoha',
        name: 'Asanoha Geometric Hemp',
        desc: 'Traditional sacred geometric lattice lines symbolizing resilience, protection, and auspicious union.',
        accent: '#5C6B73',
        eyebrow: 'Sacred Lattice',
        mood: 'Traditional sacred geometric lattice lines and serene Zen poise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f7f9fa 0%, #e0e5e8 50%, #5c6b73 100%)',
    },
    {
        id: 'holynight',
        name: 'Holy Night Starlight',
        desc: 'Sacred cathedral evening vows, glowing constellation starlight, and deep midnight sapphire.',
        accent: '#E2B653',
        eyebrow: 'Cathedral Starlight',
        mood: 'Sacred evening vows, cathedral starlight, and deep sapphire glow',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #080e1a 0%, #1b2a4a 50%, #e2b653 100%)',
    },
    {
        id: 'snowwhite',
        name: 'Snow White Crystalline',
        desc: 'Pure winter romance, crystalline frost textures, and serene silver-slate typography.',
        accent: '#708090',
        eyebrow: 'Winter Frost',
        mood: 'Pure winter romance, crystalline frost textures, and serene silver poise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8fbfe 0%, #e6f0fa 50%, #708090 100%)',
    },
    {
        id: 'teaceremony',
        name: 'Tea Ceremony Zen',
        desc: 'Kyoto tea ceremony minimalism, matcha green tones, and bamboo washi tranquility.',
        accent: '#4A5D4E',
        eyebrow: 'Kyoto Mindfulness',
        mood: 'Kyoto tea ceremony minimalism, matcha tones, and bamboo tranquility',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f5f8f5 0%, #e3ebe4 50%, #4a5d4e 100%)',
    },
    {
        id: 'anemone',
        name: 'Anemone Botanical Chic',
        desc: 'Parisian floral boutique aesthetic with monochrome anemone blossoms and delicate calligraphy.',
        accent: '#2B2D42',
        eyebrow: 'Parisian Florist',
        mood: 'Monochrome anemone blossoms, crisp paper, and delicate Parisian script',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fcfcfd 0%, #ebebf0 50%, #2b2d42 100%)',
    },
    {
        id: 'camellia',
        name: 'Camellia Tsubaki Bloom',
        desc: 'Bold crimson winter camellia petals, deep forest green accents, and celebratory Japanese poise.',
        accent: '#B71C1C',
        eyebrow: 'Winter Camellia',
        mood: 'Bold crimson winter camellia petals and deep forest greenery',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff8f9 0%, #fce4ec 50%, #b71c1c 100%)',
    },
    {
        id: 'hydrangea',
        name: 'Hydrangea Ajisai Mist',
        desc: 'Soft watercolor lilac and sky-blue hydrangea clusters evoking gentle June rain poetry.',
        accent: '#6C757D',
        eyebrow: 'June Rain Poetry',
        mood: 'Soft watercolor lilac & sky-blue hydrangea clusters in morning mist',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f9f9fd 0%, #e2e3f0 50%, #6c757d 100%)',
    },
    {
        id: 'notepaper',
        name: 'Handwritten Love Note',
        desc: 'Intimate handwritten love letter on deckled linen stationery with fountain-pen cursive notes.',
        accent: '#5D4037',
        eyebrow: 'Deckled Love Letter',
        mood: 'Handwritten love letters on deckled linen stationery with nostalgic warmth',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #faf7f5 0%, #efebe9 50%, #5d4037 100%)',
    },
    {
        id: 'petlove',
        name: 'Pet Lovers Celebration',
        desc: 'Whimsical paw print motifs, playful hand-drawn companion accents, and joyful family warmth.',
        accent: '#E67E22',
        eyebrow: 'Furry Companions',
        mood: 'Whimsical paw prints, playful companion accents, and joyful family love',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fef9f3 0%, #fdebdd 50%, #e67e22 100%)',
    },
    {
        id: 'weddingtimes',
        name: 'The Wedding Times',
        desc: 'Vintage newspaper masthead styling, editorial story columns, black & white photography, and nostalgic headlines.',
        accent: '#212529',
        eyebrow: 'Front Page Romance',
        mood: 'Vintage newspaper chronicle, editorial column layout, and nostalgic headline romance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 50%, #212529 100%)',
    },
    {
        id: 'mimosa',
        name: 'Mimosa Golden Bloom',
        desc: 'Sun-drenched golden mimosa blossom clusters, French Provençal champagne warmth, and spring garden radiance.',
        accent: '#E6A100',
        eyebrow: 'Golden Provençal',
        mood: 'Sun-drenched golden mimosa florals, botanical delicacy, and joyful warmth',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffdf2 0%, #fef7da 50%, #e6a100 100%)',
    },
    {
        id: 'oceanblue',
        name: 'Azure Ocean Breeze',
        desc: 'Deep sapphire coastal waters, sea glass reflections, Mediterranean ocean breeze, and undulating marine crests.',
        accent: '#0077B6',
        eyebrow: 'Coastal Horizon',
        mood: 'Azure waves, sea-salt mist, coastal horizons, and serene marine elegance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f0f8ff 0%, #caf0f8 50%, #0077b6 100%)',
    },
    {
        id: 'emerald',
        name: 'Emerald Gatsby Luxe',
        desc: 'Deep emerald velvet, 24-karat gold filigree borders, Art Deco symmetry, and Great Gatsby ballroom grandeur.',
        accent: '#0F5132',
        eyebrow: 'Gilded Emerald',
        mood: 'Royal emerald velvet, geometric Gatsby borders, and 1920s luxury',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #092c1b 0%, #157347 50%, #d4af37 100%)',
    },
    {
        id: 'washipaper',
        name: 'Mulberry Washi Craft',
        desc: 'Handcrafted mulberry washi paper texture, natural fiber deckled edges, gentle earth tones, and serene Zen calligraphy.',
        accent: '#7C6F57',
        eyebrow: 'Handmade Mulberry',
        mood: 'Hand-crafted mulberry washi paper, natural fiber textures, and serene Zen balance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fbf9f5 0%, #f0ebd8 50%, #7c6f57 100%)',
    },
    {
        id: 'mistveil',
        name: 'Mist Veil Dream',
        desc: 'Dreamy translucent photo veil, diffused morning luminescence, Antic Didone titling, and high-fashion romance.',
        accent: '#6C7A89',
        eyebrow: 'Ethereal Veil',
        mood: 'Ethereal misty filter veil, diffused luminescence, and cinematic poetry',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8f9fa 0%, #e2e6ea 50%, #6c7a89 100%)',
    },
    {
        id: 'linea',
        name: 'Linea Architectural',
        desc: 'Continuous architectural hairline frames, Cormorant Infant Roman serif, pristine gallery margins, and modern restraint.',
        accent: '#343A40',
        eyebrow: 'Architectural Line',
        mood: 'Continuous architectural hairline geometry, pristine gallery pacing, and modern restraint',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #e9ecef 50%, #343a40 100%)',
    },
    {
        id: 'planetarium',
        name: 'Planetarium Stardust',
        desc: 'Midnight star projector dome, glowing zodiac alignments, deep indigo starlight, and golden constellation charts.',
        accent: '#D4AF37',
        eyebrow: 'Midnight Planetarium',
        mood: 'Midnight star projector domes, glowing constellations, and celestial eternity',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #050814 0%, #111a3b 50%, #d4af37 100%)',
    },
    {
        id: 'forest',
        name: 'Evergreen Pine Forest',
        desc: 'Pacific Northwest redwood grove foliage, mountain moss tones, rustic timber warmth, and organic pine needle accents.',
        accent: '#2D5A27',
        eyebrow: 'Redwood Sanctuary',
        mood: 'Deep alpine redwood foliage, woodland moss, and organic mountain romance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f4f7f4 0%, #dbe6dc 50%, #2d5a27 100%)',
    },
    {
        id: 'jazz',
        name: 'Jazz Speakeasy Noir',
        desc: '1920s Harlem & New Orleans jazz speakeasy, warm amber bourbon glow, brass instruments, and velvet midnight rhythm.',
        accent: '#FFB703',
        eyebrow: 'Bourbon & Brass',
        mood: 'Candlelit speakeasy warmth, golden brass accents, and syncopated vintage rhythm',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #120d08 0%, #36220f 50%, #ffb703 100%)',
    },
    {
        id: 'heritage',
        name: 'Heritage Aristocrat Crest',
        desc: 'Old-world wax seals, heritage family crests, Cormorant Garamond typography, and aristocratic vintage luxury.',
        accent: '#8B263E',
        eyebrow: 'Aristocratic Crest',
        mood: 'Old-world wax seals, heritage family crests, and timeless aristocratic poise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fbf7f4 0%, #ecd8dc 50%, #8b263e 100%)',
    },
    {
        id: 'sunflower',
        name: 'Sunlit Tuscan Sunflower',
        desc: 'Radiant golden sunflowers, Italian countryside warmth, rustic olive green accents, and joyful summer sunshine.',
        accent: '#E5A910',
        eyebrow: 'Tuscan Sunshine',
        mood: 'Golden sunflower blooms, rustic warmth, and sunlit Tuscan countryside vows',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffcf0 0%, #fdf0c2 50%, #e5a910 100%)',
    },
    {
        id: 'mermaidbeach',
        name: 'Mermaid Lagoon Beach',
        desc: 'Iridescent coastal seafoam, pastel seashell tones, gentle beach tides, and sun-kissed barefoot island romance.',
        accent: '#2A9D8F',
        eyebrow: 'Seashell Lagoon',
        mood: 'Iridescent coastal seafoam, pastel seashells, and gentle island tides',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f0faf9 0%, #ccebe6 50%, #2a9d8f 100%)',
    },
    {
        id: 'passport',
        name: 'Boarding Pass & Passport',
        desc: 'Airline boarding pass styling, travel ticket barcodes, vintage visa stamps, and jetsetter destination elopements.',
        accent: '#1D3557',
        eyebrow: 'First Class Ticket',
        mood: 'Boarding pass cards, passport stamps, and a lifetime journey together',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f1faee 0%, #a8dadc 50%, #1d3557 100%)',
    },
    {
        id: 'enchanted',
        name: 'Enchanted Storybook Forest',
        desc: 'Luminescent fairy-tale forest glades, gilded storybook borders, twilight sparkle, and magical romance.',
        accent: '#7209B7',
        eyebrow: 'Fairytale Magic',
        mood: 'Luminescent fairytale forest glades, gilded stardust, and storybook magic',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #10002b 0%, #3a0ca3 50%, #7209b7 100%)',
    },
    {
        id: 'coralsea',
        name: 'Coral Sea Sunset',
        desc: 'Warm coral reef pinks, glowing tropical sunsets, playful cursive scripts, and breezy barefoot celebrations.',
        accent: '#F26419',
        eyebrow: 'Reef Twilight',
        mood: 'Warm coral sunset hues, tropical ocean twilight, and playful beachfront love',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff5f0 0%, #ffd8cc 50%, #f26419 100%)',
    },
    {
        id: 'oldpaper',
        name: 'Antiqued Vellum Parchment',
        desc: 'Time-worn vellum parchment textures, vintage deckled edges, archival sepia tones, and romantic handwritten script.',
        accent: '#6F4E37',
        eyebrow: 'Historic Vellum',
        mood: 'Aged vellum parchment textures, archival sepia tones, and timeless handwritten romance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f7f2e8 0%, #e9dec9 50%, #6f4e37 100%)',
    },
    {
        id: 'lapin',
        name: 'Le Lapin Country Cottage',
        desc: 'Whimsical French countryside cottage gardens, woodland flora, gentle bunny motifs, and pastel storybook warmth.',
        accent: '#839788',
        eyebrow: 'Provencal Cottage',
        mood: 'French cottage gardens, woodland flora, and gentle pastoral storybook warmth',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fbfaf6 0%, #e7ede8 50%, #839788 100%)',
    },
    {
        id: 'yellowsummer',
        name: 'Citron Summer Garden',
        desc: 'Zesty lemon orchard groves, Mediterranean sunshine, crisp linen whites, and sparkling outdoor champagne toasts.',
        accent: '#F4A261',
        eyebrow: 'Lemon Orchard',
        mood: 'Zesty lemon orchard groves, sunlit terrace celebrations, and sparkling citrus radiance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffbf2 0%, #fee9cc 50%, #f4a261 100%)',
    },
    {
        id: 'retroflower',
        name: '70s Retro Flower Power',
        desc: 'Groovy 1970s psychedelic flower motifs, warm mustard & avocado palettes, wavy curves, and playful retro love.',
        accent: '#D97706',
        eyebrow: 'Groovy Sunshine',
        mood: '70s retro flower power, groovy undulating waves, and joyful vintage sunshine',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fef9ee 0%, #fde8b7 50%, #d97706 100%)',
    },
    {
        id: 'daisygarden',
        name: 'Daisy Meadow Picnic',
        desc: 'Pastoral English daisy meadows, sun-dappled picnic blankets, wildflower garlands, and relaxed rustic elegance.',
        accent: '#606C38',
        eyebrow: 'Wild Daisy Lawn',
        mood: 'Gentle English daisy lawns, picnic blankets, and relaxed wildflower rustic elegance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fafbf5 0%, #e8edd5 50%, #606c38 100%)',
    },
    {
        id: 'clearblue',
        name: 'Pure Crystal Cerulean',
        desc: 'Luminescent ice-blue crystal water, transparent floating glass surfaces, and pristine modern architectural purity.',
        accent: '#0096C7',
        eyebrow: 'Crystal Waters',
        mood: 'Luminescent crystalline azure waters, transparent glass surfaces, and modern serene purity',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f3faff 0%, #d0efff 50%, #0096c7 100%)',
    },
    {
        id: 'musicfest',
        name: 'Wedding Music Festival',
        desc: 'Festival lineup typography, backstage VIP pass lanyards, bold rock concert energy, and electric celebratory vibes.',
        accent: '#E63946',
        eyebrow: 'Main Stage VIP',
        mood: 'Rock festival lineup energy, VIP wristband vibes, and electrifying celebratory excitement',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #111111 0%, #2b1115 50%, #e63946 100%)',
    },
    {
        id: 'botanicalgreen',
        name: 'Glasshouse Botanical Oasis',
        desc: 'Lush monstera and silver dollar eucalyptus foliage, greenhouse botanical glass, and deep verdant tranquility.',
        accent: '#2D6A4F',
        eyebrow: 'Verdant Glasshouse',
        mood: 'Lush tropical glasshouse foliage, eucalyptus tranquility, and deep botanical calm',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f4f9f6 0%, #cfe5d8 50%, #2d6a4f 100%)',
    },
    {
        id: 'fluidmodern',
        name: 'Tokyo Fluid Gradient',
        desc: 'Contemporary Tokyo modernism with liquid abstract shape morphs, subtle mesh blends, and forward-looking poise.',
        accent: '#4361EE',
        eyebrow: 'Tokyo Modernisme',
        mood: 'Abstract liquid shape morphs, subtle mesh gradients, and forward-looking poise',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f5f7ff 0%, #dce4ff 50%, #4361ee 100%)',
    },
    {
        id: 'springrise',
        name: 'Spring Dawn Sakura',
        desc: 'Early morning cherry blossom petals in soft rosy dawn light, watercolor wash backgrounds, and poetic rebirth.',
        accent: '#E87A90',
        eyebrow: 'Dawn Blossom',
        mood: 'Early morning cherry blossom petals, rosy dawn light, and poetic seasonal rebirth',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff7f8 0%, #fde4e9 50%, #e87a90 100%)',
    },
    {
        id: 'truelove',
        name: 'True Love Monogram',
        desc: 'Formal intertwined serif monograms, crisp monochrome ivory & charcoal contrasts, and regal black-tie vows.',
        accent: '#1F2937',
        eyebrow: 'Black-Tie Monogram',
        mood: 'Formal intertwined serif monograms, crisp monochrome ivory contrast, and black-tie elegance',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #e5e7eb 50%, #1f2937 100%)',
    },
    {
        id: 'oceanus',
        name: 'Oceanus Deep Abyssal',
        desc: 'Deep oceanic trench navy, glowing turquoise bioluminescence, rolling abyssal swells, and eternal romantic depth.',
        accent: '#0077B6',
        eyebrow: 'Abyssal Romance',
        mood: 'Deep oceanic trench navy, glowing turquoise bioluminescence, and eternal romantic depth',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #03071e 0%, #023e8a 50%, #00b4d8 100%)',
    },
    {
        id: 'airport',
        name: 'Jetsetter Runway Terminal',
        desc: 'International flight departure boards, runway landing lights, modern typography, and worldwide jetsetter unions.',
        accent: '#3A86FF',
        eyebrow: 'Runway Departure',
        mood: 'Flight departure board styling, runway lights, and international destination love',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f4f8ff 0%, #d4e5ff 50%, #3a86ff 100%)',
    },
    {
        id: 'noweddingnolife',
        name: 'No Wedding No Life',
        desc: 'High-voltage graphic poster art, bold Tokyo street fashion typography, energetic neon accents, and fearless celebration.',
        accent: '#FF0054',
        eyebrow: 'High Voltage Romance',
        mood: 'High-voltage Tokyo poster art, bold graphic typography, and fearless energetic celebration',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #16000d 0%, #4a0024 50%, #ff0054 100%)',
    },
    {
        id: 'arrangeflowers',
        name: 'Floral Arrangement Atelier',
        desc: 'Fine-art floral ikebana arrangement, pastel hydrangeas, garden rose compositions, and delicate botanical styling.',
        accent: '#B76E79',
        eyebrow: 'Ikebana Atelier',
        mood: 'Artisan floral arrangements, pastel garden blooms, and delicate ikebana harmony',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffcf9 0%, #faecef 50%, #b76e79 100%)',
    },
    {
        id: 'gradientleaf',
        name: 'Gradient Leaf Botanica',
        desc: 'Shimmering metallic ombre eucalyptus foliage, Cinzel Roman titling, and gilded botanical luxury.',
        accent: '#386641',
        eyebrow: 'Gilded Foliage',
        mood: 'Shimmering ombre eucalyptus leaves, Roman serif titling, and botanical foil luxury',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f2f7f4 0%, #cde3d5 50%, #386641 100%)',
    },
    {
        id: 'growthtale',
        name: 'Growth Tale Silhouette',
        desc: 'Poiret One Art Deco line art, romantic couple growth silhouettes, and storybook fairytale warmth.',
        accent: '#6A4C93',
        eyebrow: 'Fairytale Silhouette',
        mood: 'Art Deco line-art silhouettes, whimsical starry accents, and romantic growth chapters',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #1b122c 0%, #412966 50%, #6a4c93 100%)',
    },
    {
        id: 'innocentpetals',
        name: 'Innocent Petals Veil',
        desc: 'Pure ivory bridal veil translucency, gentle blush cherry blossom petals, and serene morning vows.',
        accent: '#E09FAD',
        eyebrow: 'Bridal Veil Petals',
        mood: 'Pure ivory veil translucency, gentle blush petals, and serene morning vows',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffbfb 0%, #fdebee 50%, #e09fad 100%)',
    },
    {
        id: 'deeporange',
        name: 'Terracotta Sienna Sunset',
        desc: 'Warm Spanish terracotta tile, burnt sienna desert sunsets, sun-baked clay arches, and Mediterranean romance.',
        accent: '#C85A32',
        eyebrow: 'Terracotta Sunset',
        mood: 'Warm Spanish terracotta tiles, burnt sienna desert glow, and sun-baked romance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8f5 0%, #fbd5c5 50%, #c85a32 100%)',
    },
    {
        id: 'hanaume',
        name: 'Hanaume Winter Plum',
        desc: 'Traditional Japanese crimson and white plum blossoms, celebratory gold accents, and auspicious winter-spring poise.',
        accent: '#A61C1C',
        eyebrow: 'Auspicious Plum',
        mood: 'Crimson winter plum blossoms, celebratory gold leaf, and auspicious spring arrival',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #fff7f7 0%, #fad6d6 50%, #a61c1c 100%)',
    },
    {
        id: 'bluebird',
        name: 'Bluebird of Happiness',
        desc: 'Classic bluebird porcelain motif, powder blue sky gradients, uplifting sweet vows, and gentle joy.',
        accent: '#4682B4',
        eyebrow: 'Bluebird Joy',
        mood: 'Symbolic bluebirds of happiness, soft sky-blue gradients, and sweet uplifting vows',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f4f9fd 0%, #d8ecf8 50%, #4682b4 100%)',
    },
    {
        id: 'gardenwedding',
        name: 'English Manor Garden',
        desc: 'Historic English country estate lawns, climbing ivy stone walls, afternoon garden rose arbors, and timeless poise.',
        accent: '#405D27',
        eyebrow: 'English Manor',
        mood: 'Historic English country estate lawns, climbing ivy, and afternoon garden tea romance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f6f8f5 0%, #dce4d7 50%, #405d27 100%)',
    },
    {
        id: 'minimumstyle',
        name: 'Minimum Swiss Modern',
        desc: 'Stark Swiss modernist grid, generous negative whitespace, black & white photography, and architectural serenity.',
        accent: '#111827',
        eyebrow: 'Swiss Minimalist',
        mood: 'Stark Swiss modernist typography, generous negative space, and architectural purity',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #f3f4f6 50%, #111827 100%)',
    },
    {
        id: 'music',
        name: 'Acoustic Symphony',
        desc: 'Classical musical stave accents, delicate acoustic violin & cello rhythm, and lyrical harmony vows.',
        accent: '#4A4E69',
        eyebrow: 'Lyrical Symphony',
        mood: 'Classical musical stave flourishes, acoustic string quartet elegance, and harmonious vows',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f7f7f9 0%, #dedfe7 50%, #4a4e69 100%)',
    },
    {
        id: 'royalblue',
        name: 'Imperial Royal Cobalt',
        desc: 'Deep royal cobalt blue, Josefin Slab modernism, gold foil embellishments, and grand ballroom majesty.',
        accent: '#00308F',
        eyebrow: 'Imperial Cobalt',
        mood: 'Deep imperial cobalt blue velvet, gilded gold leaf, and grand ballroom majesty',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #051433 0%, #002875 50%, #00308f 100%)',
    },
    {
        id: 'letter',
        name: 'Wax-Sealed Airmail',
        desc: 'Vintage airmail border chevrons, crimson wax seals, postal cancellation stamps, and transatlantic vows.',
        accent: '#B22222',
        eyebrow: 'Transatlantic Airmail',
        mood: 'Vintage airmail chevron borders, crimson wax seals, and transatlantic love letters',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fcfaf7 0%, #f6e6e6 50%, #b22222 100%)',
    },
    {
        id: 'naturalcamper',
        name: 'Glamping Pines & Starlight',
        desc: 'Cozy wilderness glamping, lantern light under the pines, campfire warmth, and mountain outdoor union.',
        accent: '#588157',
        eyebrow: 'Wilderness Glamping',
        mood: 'Alpine glamping under the pines, campfire warmth, and starlit mountain love',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f5f7f4 0%, #d8e2dc 50%, #588157 100%)',
    },
    {
        id: 'modernsquare',
        name: 'Modernist Square Gallery',
        desc: 'Balanced square photographic tiles, contemporary Tokyo gallery aesthetic, and precise editorial lines.',
        accent: '#2B2D42',
        eyebrow: 'Tokyo Square Gallery',
        mood: 'Balanced square photo tiles, Tokyo gallery curation, and precise architectural lines',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 50%, #2b2d42 100%)',
    },
    {
        id: 'japan',
        name: 'Kyoto Zen Stepping Stones',
        desc: 'Kyoto stone gardens, bamboo water spouts, tranquil cedar wood tones, and harmonious Zen balance.',
        accent: '#52796F',
        eyebrow: 'Zen Stone Garden',
        mood: 'Kyoto rock gardens, peaceful bamboo accents, and harmonious Zen tranquility',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f5f7f6 0%, #dbe3e0 50%, #52796f 100%)',
    },
    {
        id: 'weddingcake',
        name: 'Pâtisserie Tiered Cake',
        desc: 'Artisan tiered wedding cake illustration, mocha and vanilla cream tones, champagne coupes, and sweet celebration.',
        accent: '#7F5539',
        eyebrow: 'Artisan Pâtisserie',
        mood: 'Tiered artisan wedding cakes, rich mocha cream, and sweet champagne celebration',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fdf8f4 0%, #f2e3d5 50%, #7f5539 100%)',
    },
    {
        id: 'akamatsu',
        name: 'Akamatsu Red Pine',
        desc: 'Ancient Japanese red pine bonsai branches, weathered stone lanterns, deep forest wisdom, and enduring unity.',
        accent: '#780000',
        eyebrow: 'Ancient Red Pine',
        mood: 'Ancient Japanese red pine branches, weathered stone lanterns, and enduring unity',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #faf5f5 0%, #ebd3d3 50%, #780000 100%)',
    },
    {
        id: 'kasumi',
        name: 'Kasumi Mountain Haze',
        desc: 'Ethereal sumi-e watercolor morning mist floating over mountain ridges, peaceful dawn light, and poetic serenity.',
        accent: '#7F7F7F',
        eyebrow: 'Morning Mountain Mist',
        mood: 'Ethereal sumi-e watercolor mist over mountain ridges and poetic dawn serenity',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fafafa 0%, #e8e8e8 50%, #7f7f7f 100%)',
    },
    {
        id: 'konatsu',
        name: 'Konatsu Island Citrus',
        desc: 'Vibrant golden Kochi island citrus, ocean sea spray, sunny pastel yellow warmth, and sparkling cheerful love.',
        accent: '#FFB703',
        eyebrow: 'Island Citrus Breeze',
        mood: 'Golden island citrus orchards, ocean breeze, and cheerful sunny celebration',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffdf2 0%, #fee9b8 50%, #ffb703 100%)',
    },
    {
        id: 'balloonrelease',
        name: 'Celebration Balloon Release',
        desc: 'Floating pastel celebration balloons rising into endless azure skies, joyful liberation, and festive happiness.',
        accent: '#3A86FF',
        eyebrow: 'Skyward Celebration',
        mood: 'Floating pastel balloons rising into azure skies, joyful liberation, and festive love',
        tier: 'premium',
        previewGradient: 'linear-gradient(135deg, #f0f7ff 0%, #d8eaff 50%, #3a86ff 100%)',
    },
];

export const TEMPLATE_LOOKUP = Object.fromEntries(
    TEMPLATES.map((template) => [template.id, template])
) as Record<string, TemplateCatalogItem>;

export function getTemplateMeta(templateId?: string) {
    return TEMPLATE_LOOKUP[templateId || 'classic'] || TEMPLATE_LOOKUP.classic;
}
