export type TemplateCatalogItem = {
    id: string;
    name: string;
    desc: string;
    accent: string;
    eyebrow: string;
    mood: string;
    image?: string;
    tier: 'free' | 'premium';
    previewGradient: string;
};

export const FREE_TEMPLATE_IDS = [
    'classic',
    'minimal',
    'romantic',
    'luxury',
    'elopement',
    'traditional',
    'timeline',
    'rsvpfocus',
    'cinematic',
    'elegance',
    'artdeco',
    'boho',
    'whimsical',
    'urban',
    'tropical',
    'midnight',
    'sakura',
    'vogue',
    'rustic',
    'film',
    'glitch',
    'vintage',
    'editorial',
    'royal',
    'garden',
] as const;
export const LANDING_TEMPLATE_IDS = ['classic', 'minimal', 'boho', 'royal', 'midnight', 'tropical'] as const;
export const SHOWCASE_TEMPLATE_IDS = ['classic', 'minimal', 'royal', 'boho', 'urban', 'tropical'] as const;

export const TEMPLATES: TemplateCatalogItem[] = [
    {
        id: 'classic',
        name: 'Classic Elegance',
        desc: 'Timeless, centered layout with graceful serif typography.',
        accent: '#C08081',
        eyebrow: 'Timeless Romance',
        mood: 'Ivory, rose, and heirloom softness',
        image: '/templates/classic.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff9f5 0%, #f8eeea 55%, #ecd4d9 100%)',
    },
    {
        id: 'minimal',
        name: 'Modern Minimal',
        desc: 'Clean lines, high contrast, and restrained luxury.',
        accent: '#3A2A2D',
        eyebrow: 'Clean Editorial',
        mood: 'Quiet contrast and gallery-grade whitespace',
        image: '/templates/minimal.png',
        tier: 'free',
        previewGradient: 'linear-gradient(145deg, #ffffff 0%, #f4f2ef 48%, #e7dfda 100%)',
    },
    {
        id: 'romantic',
        name: 'Romantic',
        desc: 'Soft textures, script details, and nostalgic framing.',
        accent: '#B85C7A',
        eyebrow: 'Soft Love Story',
        mood: 'Powder blush, poetry, and candlelight',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8fb 0%, #f8e6ee 55%, #eed3df 100%)',
    },
    {
        id: 'luxury',
        name: 'Luxury Editorial',
        desc: 'Magazine-style composition with fashion-house drama.',
        accent: '#C5A059',
        eyebrow: 'Fashion House',
        mood: 'Black lacquer and brushed gold',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #080808 0%, #18130f 50%, #382914 100%)',
    },
    {
        id: 'elopement',
        name: 'Intimate Elopement',
        desc: 'A heartfelt layout focused on the couple and their journey.',
        accent: '#6B7A62',
        eyebrow: 'Quiet Escape',
        mood: 'Alpine light and understated intimacy',
        tier: 'free',
        previewGradient: 'linear-gradient(140deg, #f7f4ee 0%, #dfe6d7 50%, #bcc9b2 100%)',
    },
    {
        id: 'traditional',
        name: 'Traditional Ceremonial',
        desc: 'Ornate details and majestic styling for formal celebrations.',
        accent: '#8F6A45',
        eyebrow: 'Grand Ceremony',
        mood: 'Ceremonial warmth and polished heritage',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff7ed 0%, #ecd9c4 55%, #caa783 100%)',
    },
    {
        id: 'timeline',
        name: 'Timeline Based',
        desc: 'Structured around the flow of the day and guest clarity.',
        accent: '#4D5B7C',
        eyebrow: 'Structured Flow',
        mood: 'Architectural rhythm with calm precision',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 52%, #c9d4e7 100%)',
    },
    {
        id: 'rsvpfocus',
        name: 'RSVP First',
        desc: 'Guest confirmation takes center stage with a crisp layout.',
        accent: '#A0616A',
        eyebrow: 'Guest Forward',
        mood: 'High-conversion clarity with elegance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff9f7 0%, #f3e4e4 52%, #dfc4c8 100%)',
    },
    {
        id: 'cinematic',
        name: 'Media Forward',
        desc: 'A motion-led layout for sharing your love story in filmic style.',
        accent: '#C7704D',
        eyebrow: 'Cinema Frame',
        mood: 'Moody amber light and widescreen drama',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #0f1116 0%, #241b17 50%, #533427 100%)',
    },
    {
        id: 'elegance',
        name: 'Minimal Elegant',
        desc: 'Refined typography and sophisticated restraint.',
        accent: '#9B7A5E',
        eyebrow: 'Quiet Luxe',
        mood: 'Soft taupe and couture spacing',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fffcf8 0%, #f0e6dc 55%, #dcc9b6 100%)',
    },
    {
        id: 'artdeco',
        name: 'Art Deco Gold',
        desc: 'Geometric framing and opulent metallic accents.',
        accent: '#C5A059',
        eyebrow: 'Gilded Geometry',
        mood: 'Jazz-era glamour and symmetry',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #121212 0%, #241d15 50%, #5d4520 100%)',
    },
    {
        id: 'boho',
        name: 'Boho Dream',
        desc: 'Organic shapes, earthy color, and warm, freeform romance.',
        accent: '#A56D52',
        eyebrow: 'Earthy Poetry',
        mood: 'Clay, linen, and artisanal warmth',
        image: '/templates/boho.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff7ef 0%, #edd8c6 50%, #d4a27e 100%)',
    },
    {
        id: 'whimsical',
        name: 'Whimsical Garden',
        desc: 'Playful motion and airy floral delight.',
        accent: '#8D7BC4',
        eyebrow: 'Storybook Bloom',
        mood: 'Petal mist and playful detail',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff9fd 0%, #ebdef8 50%, #cdb9f3 100%)',
    },
    {
        id: 'urban',
        name: 'Industrial Urban',
        desc: 'Raw textures, stark contrast, and fashion-week edge.',
        accent: '#FF4D5A',
        eyebrow: 'City After Dark',
        mood: 'Concrete, chrome, and neon tension',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #090909 0%, #202020 55%, #4f171d 100%)',
    },
    {
        id: 'tropical',
        name: 'Tropical Paradise',
        desc: 'Vibrant color, lush framing, and destination energy.',
        accent: '#0B8F7B',
        eyebrow: 'Destination Glow',
        mood: 'Sea glass, palms, and sunset freshness',
        image: '/templates/tropical.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #effcf8 0%, #d1f4ee 48%, #7fd7c8 100%)',
    },
    {
        id: 'midnight',
        name: 'Midnight Luxury',
        desc: 'A premium dark theme with luminous gold detailing.',
        accent: '#CFB53B',
        eyebrow: 'After-Hours Luxe',
        mood: 'Champagne glow over black velvet',
        image: '/templates/midnight.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #05060a 0%, #12192d 48%, #3d3416 100%)',
    },
    {
        id: 'sakura',
        name: 'Sakura Blossom',
        desc: 'Cherry blossom softness with graceful Japanese notes.',
        accent: '#D88DA9',
        eyebrow: 'Bloom Season',
        mood: 'Petal pink and spring air',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8fb 0%, #f7e4ee 55%, #edbfd3 100%)',
    },
    {
        id: 'vogue',
        name: 'High Fashion',
        desc: 'Asymmetry, large type, and runway-confidence.',
        accent: '#111111',
        eyebrow: 'Runway Edit',
        mood: 'Monochrome confidence with couture pacing',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #ffffff 0%, #efefef 52%, #d7d7d7 100%)',
    },
    {
        id: 'rustic',
        name: 'Rustic Charm',
        desc: 'Warm timber tones, string-light softness, and cozy romance.',
        accent: '#8C6446',
        eyebrow: 'Barn Glow',
        mood: 'Honey wood and candlelit comfort',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fff8ee 0%, #ead9c4 52%, #bb8e60 100%)',
    },
    {
        id: 'film',
        name: 'Retro Film',
        desc: 'Grain, analog edges, and memory-like nostalgia.',
        accent: '#B4875C',
        eyebrow: 'Analog Memory',
        mood: 'Warm grain and silver halide softness',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #1b1815 0%, #5b4734 52%, #c49c74 100%)',
    },
    {
        id: 'glitch',
        name: 'Cyber Glitch',
        desc: 'Digital texture, chromatic accents, and avant-garde energy.',
        accent: '#4EF2E0',
        eyebrow: 'Neo Signal',
        mood: 'Cyan, magenta, and digital pulse',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #05070f 0%, #11182c 48%, #2a0f3d 100%)',
    },
    {
        id: 'vintage',
        name: 'Vintage Postcard',
        desc: 'Antique paper, old-world lettering, and keepsake charm.',
        accent: '#A67C52',
        eyebrow: 'Keepsake Paper',
        mood: 'Faded parchment and heirloom stamps',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fcf7ef 0%, #e7d8c4 55%, #c4a179 100%)',
    },
    {
        id: 'editorial',
        name: 'Editorial Chic',
        desc: 'Large-format imagery with a luxury magazine attitude.',
        accent: '#1E1E1E',
        eyebrow: 'Magazine Cover',
        mood: 'Hero photography and stark elegance',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #fefefe 0%, #ececec 50%, #d7d0cb 100%)',
    },
    {
        id: 'royal',
        name: 'Royal Proclamation',
        desc: 'Majestic darkness with heraldic gold refinement.',
        accent: '#D6B87C',
        eyebrow: 'Regal Drama',
        mood: 'Velvet halls and ceremonial gold',
        image: '/templates/royal.png',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #0c0c0c 0%, #181818 44%, #49351d 100%)',
    },
    {
        id: 'garden',
        name: 'Secret Garden',
        desc: 'Botanical elegance with lush, layered greenery.',
        accent: '#537A57',
        eyebrow: 'Botanical Estate',
        mood: 'Green canopies and conservatory light',
        tier: 'free',
        previewGradient: 'linear-gradient(135deg, #f8fbf5 0%, #d8e7d1 52%, #9fba94 100%)',
    },
];

export const TEMPLATE_LOOKUP = Object.fromEntries(
    TEMPLATES.map((template) => [template.id, template])
) as Record<string, TemplateCatalogItem>;

export function getTemplateMeta(templateId?: string) {
    return TEMPLATE_LOOKUP[templateId || 'classic'] || TEMPLATE_LOOKUP.classic;
}
