'use client';
import {useCallback,useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
export default function BriefPage(){
    const token=useParams<{token:string}>()?.token||'';
    const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [search,setSearch]=useState('');const [busy,setBusy]=useState(false);
    const load=useCallback(async()=>{const response=await fetch(`/api/public/brief?token=${encodeURIComponent(token)}`,{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);},[token]);
    useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
    async function respond(guestId?:string){setBusy(true);setError('');try{const response=await fetch('/api/public/brief',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,version:data.item.version,guestId})});const result=await response.json();if(!response.ok)throw new Error(result.error);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
    return <main className="min-h-screen bg-neutral p-4 sm:p-8"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-6 space-y-4">{error&&<p role="alert">{error}</p>}{!data?<p>Loading briefing…</p>:<><h1 className="text-3xl font-serif">{data.wedding.bride_name} &amp; {data.wedding.groom_name}</h1><h2 className="text-xl font-bold">{data.item.title}</h2><p>{data.wedding.venue_name} · {data.wedding.venue_address}</p><p>{data.item.due_at?new Date(data.item.due_at).toLocaleString():''}</p><p className="whitespace-pre-wrap">{data.item.notes}</p><p>Contact: {data.wedding.contact_person}</p>{data.item.kind==='helper'?<><label className="block">Find a guest<input className="block w-full min-h-12 rounded-xl border p-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or guest code"/></label>{data.guests.filter((g:any)=>`${g.guest_name} ${g.guest_code}`.toLowerCase().includes(search.toLowerCase())).map((g:any)=><div className="flex justify-between border-t py-3 gap-3" key={g.id}><div><strong>{g.guest_name}</strong><p>{g.table_assignment||'Ask reception'} · {g.num_guests} people</p></div><button className="min-h-12 border rounded-xl p-3" disabled={busy||!!g.checked_in_at} onClick={()=>void respond(g.id)}>{g.checked_in_at?'Checked in':'Check in'}</button></div>)}</>:<button disabled={busy||data.item.status==='done'} className="min-h-12 rounded-xl bg-primary px-5 text-white" onClick={()=>void respond()}>{data.item.status==='done'?'Acknowledged':'I have reviewed this briefing'}</button>}<p className="text-sm">Keep this link private. Your access is limited to this briefing.</p></>}</div></main>;
}
