-- QuickWeds marketing nurture automation.
-- Run this in the Supabase SQL editor before enabling /api/cron/marketing-nurture.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.marketing_nurture_subscribers (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'completed', 'converted', 'unsubscribed', 'bounced')),
    sequence_step INTEGER NOT NULL DEFAULT 0 CHECK (sequence_step >= 0),
    next_send_at TIMESTAMP WITH TIME ZONE,
    last_sent_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    converted_at TIMESTAMP WITH TIME ZONE,
    unsubscribed_at TIMESTAMP WITH TIME ZONE,
    unsubscribe_token UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS marketing_nurture_unsubscribe_token_idx
ON public.marketing_nurture_subscribers (unsubscribe_token);

CREATE INDEX IF NOT EXISTS marketing_nurture_due_idx
ON public.marketing_nurture_subscribers (status, next_send_at)
WHERE status = 'active';

CREATE TABLE IF NOT EXISTS public.marketing_nurture_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    email TEXT NOT NULL,
    sequence_step INTEGER NOT NULL,
    subject TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('sent', 'failed')),
    provider_message_id TEXT,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS marketing_nurture_events_user_idx
ON public.marketing_nurture_events (user_id, created_at DESC);

ALTER TABLE public.marketing_nurture_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_nurture_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_read_own_marketing_nurture_subscription" ON public.marketing_nurture_subscribers;
CREATE POLICY "users_read_own_marketing_nurture_subscription"
ON public.marketing_nurture_subscribers
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "users_read_own_marketing_nurture_events" ON public.marketing_nurture_events;
CREATE POLICY "users_read_own_marketing_nurture_events"
ON public.marketing_nurture_events
FOR SELECT
USING (auth.uid() = user_id);

NOTIFY pgrst, 'reload schema';
