import {NextRequest,NextResponse} from 'next/server';
import {getSupabaseAdminClient} from '@/lib/supabase-admin';
import {escapeHtml} from '@/lib/seat-finder';
import {isRsvpClosed} from '@/lib/event-time';
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){
    const {id}=await params;const db=getSupabaseAdminClient() as any;
    const {data:wedding,error}=await db.from('weddings').select('id,bride_name,groom_name,is_published,rsvp_deadline,event_timezone,operations_settings').eq('id',id).is('deleted_at',null).maybeSingle();
    if(error||!wedding?.is_published)return new NextResponse('Invitation unavailable.',{status:404});
    const origins=(Array.isArray(wedding.operations_settings?.embedOrigins)?wedding.operations_settings.embedOrigins:[]).filter((value:unknown)=>typeof value==='string'&&/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(value));
    const closed=isRsvpClosed(wedding.rsvp_deadline,wedding.event_timezone);
    const idJson=JSON.stringify(id).replace(/</g,'\\u003c');
    const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wedding RSVP</title><style>body{font:16px system-ui;margin:0;padding:20px;color:#342b2e}label{display:block;margin:14px 0}input,select,button{font:inherit;box-sizing:border-box;width:100%;min-height:48px;padding:12px;border:1px solid #d9cdd1;border-radius:12px}button{background:#a84861;color:white}p{line-height:1.5}</style></head><body><h1>${escapeHtml(wedding.bride_name)} &amp; ${escapeHtml(wedding.groom_name)}</h1>${closed?'<p>Responses are closed. Please contact the couple for changes.</p>':`<form><label>Your full name<input name="guestName" required maxlength="200" autocomplete="name"></label><label>Email for confirmation<input name="guestEmail" type="email" autocomplete="email"></label><label>Will you attend?<select name="attendance"><option value="Yes">Yes</option><option value="No">No</option></select></label><label>Total people, including you and children<input name="numGuests" type="number" min="1" max="50" value="1" required></label><button>Send RSVP</button></form><p role="status" id="status"></p>`}<p><a href="/w/${encodeURIComponent(id)}#rsvp" target="_blank" rel="noopener">Open the full invitation and RSVP form</a></p><script>const form=document.querySelector('form');if(form)form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;const status=document.getElementById('status');try{const response=await fetch('/api/public/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(form)),weddingId:${idJson}})});const result=await response.json();if(!response.ok)throw new Error(result.error);status.textContent='Your response is saved. ';const link=document.createElement('a');link.href=result.guestPass;link.target='_blank';link.rel='noopener';link.textContent='Open your private guest pass';status.append(link);form.hidden=true;}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});</script></body></html>`;
    return new NextResponse(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'','Content-Security-Policy':`default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; form-action 'self'; frame-ancestors 'self' ${origins.join(' ')}; base-uri 'none'; object-src 'none'`,'Referrer-Policy':'no-referrer'}});
}
